<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="ResourceStatusProcess" targetNamespace="http://RemJDBCModule/ResourceStatusProcessArtifacts" xmlns:ns0="http://Remittance_JDBC_Common_Toolkit_Library/ResourceStatusIntf" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/">
  <plnk:partnerLinkType name="ResourceStatusIntfPLT">
    <plnk:role name="Interface">
      <plnk:portType name="ns0:ResourceStatusIntf"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="ResourceStatusIntfPLT1">
    <plnk:role name="Interface">
      <plnk:portType name="ns0:ResourceStatusIntf"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="ResourceStatusIntf.wsdl" namespace="http://Remittance_JDBC_Common_Toolkit_Library/ResourceStatusIntf"/>
</wsdl:definitions>