<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/MappingAuditHistoryReq_req_1.map" md5sum="c4e2cc9ee64ad2fe8d5e0f481c2f1e8e" version="8.0.400" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		MappingAuditHistoryReq_req_1.map
*   Map declaration(s):	MappingAuditHistoryReq_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FRemittance_JDBC_Common_Toolkit_Library%252FAuditHistoryIntf%257DupsertAuditHistoryRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FRemittance_JDBC_Common_Toolkit_Implementation%252FJDBCImport%257DupsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBGRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:math="http://exslt.org/math"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:exsl="http://exslt.org/common"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:in2="http://RSD"
    xmlns:in4="http://Remittance_JDBC_Common_Toolkit_Library/AuditHistoryIntf"
    xmlns:in3="http://TCBT24Library"
    xmlns:io5="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io2="http://www.w3.org/2005/08/addressing"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in5="http://Remittance_JDBC_Common_Toolkit_Library/InsertRemittanceCase"
    xmlns:in6="http://RJDBCCT"
    xmlns:in="wsdl.http://Remittance_JDBC_Common_Toolkit_Library/AuditHistoryIntf"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceremittance_transactionlist"
    xmlns:out6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancedocument"
    xmlns:out9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancegeneral_informationlist"
    xmlns:out8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceresource_status"
    xmlns:out48="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_approval_historybg"
    xmlns:out3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceremittance_transactionbg"
    xmlns:out11="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceremittance_transactionupdateallinput"
    xmlns:out49="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet24_entry_informationcontainer"
    xmlns:out12="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_approval_historycontainer"
    xmlns:out2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceresource_statuslist"
    xmlns:out46="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancegeneral_informationbg"
    xmlns:out5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_audit_historyupdateallinputbg"
    xmlns:out47="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_case_relationshipbg"
    xmlns:out4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancedocumentbatchresult"
    xmlns:out10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceremittance_transactionupdateallinputbg"
    xmlns:out41="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancedocumentbg"
    xmlns:out19="http://com/ibm/j2ca/fault"
    xmlns:out40="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_audit_historyupdateallinput"
    xmlns:out18="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceresource_statuscontainer"
    xmlns:out17="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceaccounting_informationlistbg"
    xmlns:out80="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_case_relationshipupdateallinputbg"
    xmlns:out45="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancegeneral_informationcontainer"
    xmlns:out16="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet24_entry_informationlist"
    xmlns:out81="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet24_entry_informationbg"
    xmlns:out44="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/existsresult/existsresult"
    xmlns:out15="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet24_entry_informationupdateallinput"
    xmlns:out14="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancedocumentlistbg"
    xmlns:out43="http://com/ibm/j2ca/fault/afcfault"
    xmlns:out13="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bulkoperationresult/deleteallresult"
    xmlns:out42="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_case_relationshiplistbg"
    xmlns:out84="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_approval_historyupdateallinputbg"
    xmlns:out85="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet24_entry_informationlistbg"
    xmlns:out82="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_approval_history"
    xmlns:out83="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_approval_historylistbg"
    xmlns:out88="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_case_info"
    xmlns:out86="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_audit_historybg"
    xmlns:out87="wsdl.http://Remittance_JDBC_Common_Toolkit_Implementation/JDBCImport"
    xmlns:out57="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceaccounting_information"
    xmlns:out58="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_case_relationshipupdateallinput"
    xmlns:out59="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_case_infobg"
    xmlns:out50="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancegeneral_informationupdateallinput"
    xmlns:out52="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_case_relationship"
    xmlns:out51="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_approval_historybatchresult"
    xmlns:out54="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceaccounting_informationlist"
    xmlns:out53="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceresource_statusupdateallinputbg"
    xmlns:out56="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet24_entry_informationupdateallinputbg"
    xmlns:out55="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_case_infoupdateallinputbg"
    xmlns:out69="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_case_infolistbg"
    xmlns:out68="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_case_infobatchresult"
    xmlns:out28="http://Remittance_JDBC_Common_Toolkit_Implementation/JDBCImport"
    xmlns:out29="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancegeneral_informationupdateallinputbg"
    xmlns:out26="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_approval_historylist"
    xmlns:out27="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancegeneral_information"
    xmlns:out24="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bulkoperationresult/updateallresult"
    xmlns:out25="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancegeneral_informationlistbg"
    xmlns:out23="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceremittance_transactionbatchresult"
    xmlns:out22="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceaccounting_informationbg"
    xmlns:out21="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceaccounting_informationupdateallinput"
    xmlns:out20="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_audit_history"
    xmlns:out66="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_case_infocontainer"
    xmlns:out67="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancegeneral_informationbatchresult"
    xmlns:out64="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancedocumentupdateallinput"
    xmlns:out65="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancedocumentcontainer"
    xmlns:out62="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceaccounting_informationbatchresult"
    xmlns:out63="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceaccounting_informationupdateallinputbg"
    xmlns:out60="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_case_infolist"
    xmlns:out61="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceresource_statusbatchresult"
    xmlns:out79="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_audit_historycontainer"
    xmlns:out39="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceresource_statusbg"
    xmlns:out35="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceremittance_transactioncontainer"
    xmlns:out36="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_approval_historyupdateallinput"
    xmlns:out37="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceresource_statuslistbg"
    xmlns:out38="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_case_infoupdateallinput"
    xmlns:out32="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_audit_historylistbg"
    xmlns:out31="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceaccounting_informationcontainer"
    xmlns:out34="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceremittance_transactionlistbg"
    xmlns:out70="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:out33="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_case_relationshipbatchresult"
    xmlns:out30="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_case_relationshiplist"
    xmlns:out75="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_audit_historylist"
    xmlns:out76="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet24_entry_informationbatchresult"
    xmlns:out77="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancedocumentupdateallinputbg"
    xmlns:out78="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_case_relationshipcontainer"
    xmlns:out71="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet_remittance_audit_historybatchresult"
    xmlns:out72="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancedocumentlist"
    xmlns:out73="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceresource_statusupdateallinput"
    xmlns:out74="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittanceremittance_transaction"
    xmlns:out="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bpm_sor_remittancet24_entry_information"
    xmlns:map="http://RemJDBCModule/xslt/MappingAuditHistoryReq_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="math str set date exsl map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io3:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:MappingAuditHistoryReq_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io3:smo" mode="map:MappingAuditHistoryReq_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io3:smo" to "io3:smo".  -->
  <xsl:template match="io3:smo"  mode="map:MappingAuditHistoryReq_req_1">
    <io3:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out87:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBGRequestMsg'"/>
        </xsl:attribute>
        <out28:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBG>
          <out28:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBGInput>
            <!-- a structural mapping: "body/in4:upsertAuditHistory/input1/remittanceAuditHistory"(RemittanceAuditHistory) to "Bpm_Sor_RemittanceT_Remittance_Audit_History"(Bpm_Sor_RemittanceT_Remittance_Audit_History) -->
            <xsl:apply-templates select="body/in4:upsertAuditHistory/input1/remittanceAuditHistory" mode="localRemittanceAuditHistoryToBpm_Sor_RemittanceT_Remittance_Audit_History_763267204"/>
          </out28:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBGInput>
        </out28:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBG>
      </body>
    </io3:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io3:smo" to "io3:smo".  -->
  <xsl:template name="map:MappingAuditHistoryReq_req_12">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out87:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBGRequestMsg'"/>
      </xsl:attribute>
      <out28:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBG>
        <out28:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBGInput>
          <!-- a structural mapping: "$smo/body/in4:upsertAuditHistory/input1/remittanceAuditHistory"(RemittanceAuditHistory) to "Bpm_Sor_RemittanceT_Remittance_Audit_History"(Bpm_Sor_RemittanceT_Remittance_Audit_History) -->
          <xsl:apply-templates select="$smo/body/in4:upsertAuditHistory/input1/remittanceAuditHistory" mode="localRemittanceAuditHistoryToBpm_Sor_RemittanceT_Remittance_Audit_History_763267204"/>
        </out28:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBGInput>
      </out28:upsertBpm_Sor_RemittanceT_Remittance_Audit_HistoryBG>
    </body>
  </xsl:template>

  <!-- This rule represents an element mapping: "remittanceAuditHistory" to "Bpm_Sor_RemittanceT_Remittance_Audit_History".  -->
  <xsl:template match="remittanceAuditHistory"  mode="localRemittanceAuditHistoryToBpm_Sor_RemittanceT_Remittance_Audit_History_763267204">
    <Bpm_Sor_RemittanceT_Remittance_Audit_History>
      <!-- a simple data mapping: "in6:auditId"(string) to "audit_id"(string) -->
      <xsl:if test="in6:auditId">
        <audit_id>
          <xsl:value-of select="in6:auditId"/>
        </audit_id>
      </xsl:if>
      <!-- a simple data mapping: "in6:caseId"(string) to "case_id"(string) -->
      <xsl:if test="in6:caseId">
        <case_id>
          <xsl:value-of select="in6:caseId"/>
        </case_id>
      </xsl:if>
      <!-- a simple data mapping: "in6:taskName"(string) to "task_name"(string) -->
      <xsl:if test="in6:taskName">
        <task_name>
          <xsl:value-of select="in6:taskName"/>
        </task_name>
      </xsl:if>
      <!-- a simple data mapping: "in6:taskId"(int) to "task_id"(decimal) -->
      <xsl:if test="in6:taskId">
        <task_id>
          <xsl:value-of select="in6:taskId"/>
        </task_id>
      </xsl:if>
      <!-- a simple data mapping: "in6:userLogin"(string) to "user_login_id"(string) -->
      <xsl:if test="in6:userLogin">
        <user_login_id>
          <xsl:value-of select="in6:userLogin"/>
        </user_login_id>
      </xsl:if>
      <!-- a simple data mapping: "in6:userName"(string) to "user_name"(string) -->
      <xsl:if test="in6:userName">
        <user_name>
          <xsl:value-of select="in6:userName"/>
        </user_name>
      </xsl:if>
      <!-- a simple data mapping: "in6:userRole"(string) to "user_role"(string) -->
      <xsl:if test="in6:userRole">
        <user_role>
          <xsl:value-of select="in6:userRole"/>
        </user_role>
      </xsl:if>
      <!-- a simple data mapping: "in6:action"(string) to "action"(string) -->
      <xsl:if test="in6:action">
        <action>
          <xsl:value-of select="in6:action"/>
        </action>
      </xsl:if>
      <!-- a simple data mapping: "in6:status"(string) to "status"(string) -->
      <xsl:if test="in6:status">
        <status>
          <xsl:value-of select="in6:status"/>
        </status>
      </xsl:if>
      <!-- a simple data mapping: "in6:startDate"(dateTime) to "start_date"(dateTime) -->
      <xsl:if test="in6:startDate">
        <start_date>
          <xsl:value-of select="in6:startDate"/>
        </start_date>
      </xsl:if>
      <!-- a simple data mapping: "in6:endDate"(dateTime) to "end_date"(dateTime) -->
      <xsl:if test="in6:endDate">
        <end_date>
          <xsl:value-of select="in6:endDate"/>
        </end_date>
      </xsl:if>
      <!-- a simple data mapping: "in6:comment"(string) to "comments"(string) -->
      <xsl:if test="in6:comment">
        <comments>
          <xsl:value-of select="in6:comment"/>
        </comments>
      </xsl:if>
    </Bpm_Sor_RemittanceT_Remittance_Audit_History>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
